#!/usr/bin/env python3
"""
build_rooms_seed.py

Scan a list of pages (local files or URLs) for links like:
  <a href="room.php?room=happy-hour">Happy Hour</a>

…and generate a PHP $roomsSeed array with unique slugs.

Requirements:
    pip install requests beautifulsoup4
"""

import os
from pathlib import Path
from urllib.parse import urlparse, parse_qs
import requests
from bs4 import BeautifulSoup

# TODO: Edit this list with your actual pages:
# - Local files: r"C:\ampps\www\lensshare\index.php"
# - URLs: "https://lensshare.co/technology.php"
PAGES = [
    # Examples (comment these out and add your own):
    # r"C:\ampps\www\lensshare\index.php",
    # r"C:\ampps\www\lensshare\technology.php",
    # "https://lensshare.co/index.php",
    # "https://lensshare.co/technology.php",
    "https://lensshare.co/work.php",
    "https://lensshare.co/sports.php",
    "https://lensshare.co/education.php",
    "https://lensshare.co/entertainment.php",
    "https://lensshare.co/health.php",
    "https://lensshare.co/relationships.php",
    "https://lensshare.co/technology.php"
]

def is_url(path_or_url: str) -> bool:
    return path_or_url.startswith("http://") or path_or_url.startswith("https://")


def load_html(source: str) -> str:
    """Return HTML string from a local file or URL."""
    if is_url(source):
        resp = requests.get(source, timeout=10)
        resp.raise_for_status()
        return resp.text
    else:
        # local file
        p = Path(source)
        if not p.is_file():
            raise FileNotFoundError(f"File not found: {source}")
        return p.read_text(encoding="utf-8", errors="ignore")


def extract_room_links(html: str):
    """Yield (slug, name) pairs from <a href="room.php?room=...">text</a>."""
    soup = BeautifulSoup(html, "html.parser")
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if "room.php" not in href:
            continue
        if "room=" not in href:
            continue

        # Handle href like "room.php?room=happy-hour" or "/path/room.php?room=xyz"
        parsed = urlparse(href)
        qs = parse_qs(parsed.query)
        room_vals = qs.get("room") or qs.get("space")  # in case you ever use ?space=
        if not room_vals:
            # fallback: try simple parse if href is like "room.php?room=slug"
            # and urlparse didn't catch it due to missing scheme
            if "?" in href:
                query_part = href.split("?", 1)[1]
                qs2 = parse_qs(query_part)
                room_vals = qs2.get("room") or qs2.get("space")
            if not room_vals:
                continue

        slug = room_vals[0].strip()
        if not slug:
            continue

        name = a.get_text(strip=True)
        if not name:
            # if no visible text, we can skip or use slug
            name = slug

        yield slug, name


def php_escape(s: str) -> str:
    """Escape a Python string for safe use inside a single-quoted PHP string."""
    s = s.replace("\\", "\\\\")   # escape backslashes first
    s = s.replace("'", "\\'")     # escape single quotes
    return s


def main():
    if not PAGES:
        print("Please edit PAGES in this script to include your .php files or URLs.")
        return

    rooms = {}  # slug -> name
    for src in PAGES:
        try:
            html = load_html(src)
        except Exception as e:
            print(f"Warning: could not load {src}: {e}")
            continue

        for slug, name in extract_room_links(html):
            rooms.setdefault(slug, name)

    # ---- build ordered room list ----
    ordered_rooms = []

    # Always include Main Room first, even if it wasn't scraped
    ordered_rooms.append(('main', 'Main Room'))

    # Then add all scraped rooms, skipping 'main' if it happened to be there
    for slug, name in rooms.items():
        if slug == 'main':
            continue
        ordered_rooms.append((slug, name))

    # ---- Write output file ----
    OUTPUT_FILE = "rooms_seed.php"
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("<?php\n")
        f.write("// Auto-generated by build_rooms_seed.py\n")
        f.write("$roomsSeed = [\n")
        f.write("    // First room is the Main Room (slug 'main')\n")

        for slug, name in ordered_rooms:
            f.write("    [\n")
            f.write(f"        'slug'       => '{php_escape(slug)}',\n")
            f.write(f"        'name'       => '{php_escape(name)}',\n")
            f.write( "        'created_at' => $now,\n")
            f.write( "        'is_active'  => 1,\n")
            f.write("    ],\n")

        f.write("];\n")

    print(f"Wrote PHP roomsSeed array to: {OUTPUT_FILE}")



if __name__ == "__main__":
    main()
